CREATE DATABASE mocox_test;
USE mocox_test;

CREATE TABLE table1 (
  muid BIGINT UNSIGNED NOT NULL,
  fixed BINARY(31) NOT NULL,
  struct BLOB,
  created_on TIMESTAMP NOT NULL DEFAULT 0,
  PRIMARY KEY (muid)
) DEFAULT CHARSET=BINARY;
